AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Cloud Resume Challenge backend infrastructure

Parameters:
  TableName:
    Type: String
    Default: visitor-counter
    Description: Name of the existing DynamoDB table

Resources:
  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: counter.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref TableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TableName
      Events:
        GetVisitorCount:
          Type: Api
          Properties:
            Path: /count
            Method: get

Outputs:
  ApiUrl:
    Description: URL of the API endpoint
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/count"