# GitHub Actions workflow for backend testing and deployment
name: Backend Deploy

# Trigger the workflow on push or pull request to main branch
on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main

# Define jobs for testing and deployment
jobs:
 # Test job - runs Python tests
 test:
   runs-on: ubuntu-latest
   steps:
     # Check out repository code
     - uses: actions/checkout@v2
     
     # Set up Python environment
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.9'
         
     # Install test dependencies
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
         pip install pytest pytest-mock boto3 botocore
         
     # Run pytest test suite
     - name: Run tests
       run: |
         python -m pytest tests/

 # Deploy job - deploys to AWS using SAM
 deploy:
   needs: test    # Only deploy if tests pass
   runs-on: ubuntu-latest
   steps:
     # Check out repository code
     - uses: actions/checkout@v2
     
     # Set up Python environment
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.9'
         
     # Configure AWS credentials for deployment
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v1
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
         
     # Install AWS SAM CLI for serverless deployment
     - name: Install AWS SAM CLI
       uses: aws-actions/setup-sam@v2
       with:
         use-installer: true
         
     # Build SAM application
     - name: SAM Build
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
         sam build
         
     # Deploy SAM application
     - name: SAM Deploy
       run: |
         # Delete existing stack if it exists
         aws cloudformation delete-stack --stack-name cloud-resume-backend || true
         aws cloudformation wait stack-delete-complete --stack-name cloud-resume-backend || true
         
         # Deploy new stack
         sam deploy --no-confirm-changeset \
           --no-fail-on-empty-changeset \
           --stack-name cloud-resume-backend \
           --capabilities CAPABILITY_IAM \
           --resolve-s3 \
           --parameter-overrides TableName=visitor-counter