name: Backend Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-mock boto3 botocore
          
      - name: Run tests
        run: |
          python -m pytest tests/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
          
      - name: SAM Build
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sam build
          
      - name: SAM Deploy
        run: |
          aws cloudformation delete-stack --stack-name cloud-resume-backend || true
          aws cloudformation wait stack-delete-complete --stack-name cloud-resume-backend || true
          sam deploy --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name cloud-resume-backend \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --parameter-overrides TableName=visitor-counter